spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/inssagram
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${password}
