spring:
  jwt:
    secret-key: ${key}
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/inssagram
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${password}
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "inssagramAuthentication@gmail.com"
    password: ${smtp}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
